// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentACar.Data;

#nullable disable

namespace RentACar.Migrations
{
    [DbContext(typeof(RentACarDbContext))]
    [Migration("20260810075020_UserEklendiv2")]
    partial class UserEklendiv2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RentACar.Model.Araba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArabaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ArabaFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ArabaYasi")
                        .HasColumnType("int");

                    b.Property<int>("CarModeliID")
                        .HasColumnType("int");

                    b.Property<float>("ToplamKm")
                        .HasColumnType("real");

                    b.Property<int>("VitesID")
                        .HasColumnType("int");

                    b.Property<int>("YakitID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarModeliID");

                    b.HasIndex("VitesID");

                    b.HasIndex("YakitID");

                    b.ToTable("Arabalarr");
                });

            modelBuilder.Entity("RentACar.Model.CarModeli", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MarkaId")
                        .HasColumnType("int");

                    b.Property<string>("ModelAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MarkaId");

                    b.ToTable("CarModelleri");
                });

            modelBuilder.Entity("RentACar.Model.Marka", b =>
                {
                    b.Property<int>("MarkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarkaId"));

                    b.Property<string>("MarkaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MarkaId");

                    b.ToTable("Markalar");
                });

            modelBuilder.Entity("RentACar.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RentACar.Model.Vites", b =>
                {
                    b.Property<int>("VitesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VitesId"));

                    b.Property<string>("VitesTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VitesId");

                    b.ToTable("Vitesler");
                });

            modelBuilder.Entity("RentACar.Model.Yakit", b =>
                {
                    b.Property<int>("YakitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YakitId"));

                    b.Property<string>("YakitAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("YakitId");

                    b.ToTable("Yakitlar");
                });

            modelBuilder.Entity("RentACar.Model.Araba", b =>
                {
                    b.HasOne("RentACar.Model.CarModeli", "CarModeli")
                        .WithMany("Arabalar")
                        .HasForeignKey("CarModeliID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentACar.Model.Vites", "Vites")
                        .WithMany()
                        .HasForeignKey("VitesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentACar.Model.Yakit", "Yakit")
                        .WithMany()
                        .HasForeignKey("YakitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarModeli");

                    b.Navigation("Vites");

                    b.Navigation("Yakit");
                });

            modelBuilder.Entity("RentACar.Model.CarModeli", b =>
                {
                    b.HasOne("RentACar.Model.Marka", "Marka")
                        .WithMany("CarModelleri")
                        .HasForeignKey("MarkaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marka");
                });

            modelBuilder.Entity("RentACar.Model.CarModeli", b =>
                {
                    b.Navigation("Arabalar");
                });

            modelBuilder.Entity("RentACar.Model.Marka", b =>
                {
                    b.Navigation("CarModelleri");
                });
#pragma warning restore 612, 618
        }
    }
}
